In [1]:
from sklearn.utils import shuffle
import pandas as pd
import numpy as np
from sklearn import linear_model, preprocessing

dataset = pd.read_csv('k-nn/Dataset.csv')
data = dataset.iloc[:,1:] 

Encoding Categorical data into Numerical Data

In [2]:
le = preprocessing.LabelEncoder()
buying = le.fit_transform(list(dataset["buying"]))
maint = le.fit_transform(list(dataset["maint"]))
door = le.fit_transform(list(dataset["door"]))
persons = le.fit_transform(list(dataset["persons"]))
lug_boot = le.fit_transform(list(dataset["lug_boot"]))
safety = le.fit_transform(list(dataset["safety"]))
cls = le.fit_transform(list(dataset["class"]))
print(buying)
print(maint)
print(door)
print(persons)
print(lug_boot)
print(safety)
print(cls)

[3 3 3 ... 1 1 1]
[3 3 3 ... 1 1 1]
[0 0 0 ... 3 3 3]
[0 0 0 ... 2 2 2]
[2 2 2 ... 0 0 0]
[1 2 0 ... 1 2 0]
[2 2 2 ... 2 1 3]


Splitting Dataset

In [8]:
from sklearn.model_selection import train_test_split

predict = "class"
x = list(zip(buying, maint, door, persons, lug_boot, safety)) # features
y = list(cls) # labels
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier


neighbors = 9
model = KNeighborsClassifier(n_neighbors=neighbors)
model.fit(x_train, y_train)

acc = model.score(x_test, y_test) ### akurasi model
print(acc)