Encoding Categorical Data

Encoding Independent Data

In [4]:
### NOTES
### ColumnTransformer digunakan utk mengubah kolom kumpulan data secara berbeda.
### Ini memungkinkan utk menerapkan transformasi berbeda ke subkumpulan kolom berbeda dalam kumpulan data 
### parameter transformer=[('label', transformer_yg_dipakai, [kolom_yg_diterapkan])

### Independent variable (variabel bebas) adalah variabel yang diubah atau dimanipulasi dalam penelitian

###  Independent variable dianggap sebagai penyebab, sedangkan dependent variable merupakan hasil atau reaksi dari perubahan independent variable.

from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
import pandas as pd 
import numpy as np
 

#* importing dataset
dataset = pd.read_csv('Dataset.csv') 
x = dataset.iloc[:, :-1]   



#* taking care of missing data
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x.iloc[:, 1:3])
x.iloc[:, 1:3] = imputer.transform(x.iloc[:, 1:3]) 

#* Encoding
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
transformedX = np.array(ct.fit_transform(x)) 
transformedX = transformedX.astype(int)

print(transformedX)

[[    1     0     0    44 72000]
 [    0     0     1    27 48000]
 [    0     1     0    30 54000]
 [    0     0     1    38 61000]
 [    0     1     0    40 63777]
 [    1     0     0    35 58000]
 [    0     0     1    38 52000]
 [    1     0     0    48 79000]
 [    0     1     0    50 83000]
 [    1     0     0    37 67000]]


Encoding Dependent Variable

In [3]:
### ### Dependent variable (variabel terikat) adalah variabel yang diukur atau diamati untuk melihat dampak perubahan dalam independent variable
### Label Encoder digunakan untuk mengubah label atau nilai target yang bersifat kategorikal menjadi angka.
### Misalnya, ketika Anda memiliki label seperti "merah," "biru," dan "hijau," Anda dapat menggunakan LabelEncoder 
### untuk mengubahnya menjadi 0, 1, dan 2.

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = dataset.iloc[: , -1]
y = le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]
