In [6]:
import numpy as np

matriks = np.random.randint(1,5,(3,30)) # generate array with 2 row, 30 column containing random number from 1-4
print(matriks)


#* -- NOTE --
# random.randint() -> generate random number
# random.randint(low, high, size) 
# parameter low = the lowest number
# parameter high = the highest number
# parameter size() = generate random array
# parameter size(5) generate 1D array 
# parameter size(2,4) generate 2D array with 2 row, 4 collumn

[[3 2 4 4 1 4 4 1 2 4 4 3 2 2 1 1 1 1 3 2 2 3 3 3 1 1 1 4 2 4]
 [1 2 2 1 1 4 3 1 4 1 1 4 2 3 2 4 3 3 3 4 2 4 2 1 1 1 2 2 2 2]
 [1 4 3 4 1 3 3 1 3 2 2 1 4 3 1 3 4 4 4 4 1 4 1 3 4 1 3 2 1 4]]
