Splitting the dataset into the Training set and Test set

In [32]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
import pandas as pd 
import numpy as np
#* importing dataset
dataset = pd.read_csv('Dataset.csv') 

x = dataset.iloc[:, :-1]  
y = dataset.iloc[: , -1]  
z = dataset.iloc[[2]] 



#* taking care of missing data
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x.iloc[:, 1:3])
x.iloc[:, 1:3] = imputer.transform(x.iloc[:, 1:3]) 

#* Encoding
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x)) 
x = x.astype(int)

print(x)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = dataset.iloc[: , -1]
y = le.fit_transform(y)
print(y)





[[    1     0     0    44 72000]
 [    0     0     1    27 48000]
 [    0     1     0    30 54000]
 [    0     0     1    38 61000]
 [    0     1     0    40 63777]
 [    1     0     0    35 58000]
 [    0     0     1    38 52000]
 [    1     0     0    48 79000]
 [    0     1     0    50 83000]
 [    1     0     0    37 67000]]
[0 1 0 0 1 1 0 1 0 1]


In [33]:
### train_test_split() digunakan untuk membagi dataset menjadi dua subset yang terpisah: 
### subset pelatihan (training set) dan subset pengujian (test set).
### sehingga Anda dapat melatih model pada satu bagian dan menguji model pada bagian lainnya.

### Parameter test_size mengontrol proporsi data yang akan diambil sebagai pengujian.
### Parameter random_state digunakan untuk mengontrol inisialisasi generator angka acak, sehingga hasil split data dapat direproduksi.

from sklearn.model_selection import train_test_split
### Memisahkan dataset menjadi subset pelatihan dan pengujian (dalam contoh ini, 80% pelatihan, 20% pengujian)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

print(x_train)



(8, 5)


In [34]:
print(x_test)

[[    0     1     0    30 54000]
 [    1     0     0    37 67000]]


In [35]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [36]:
print(y_test)

[0 1]
